services:
  # Base de datos
  db:
    image: mysql:8.0
    container_name: tranquil_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '12345678'
      MYSQL_DATABASE: salud_mental
      MYSQL_ROOT_HOST: '%'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    networks:
      - tranquil_net

  # Backend de Autenticación (Spring Boot)
  springboot-app:
    build:
      context: ./Tranquil_Conecct_Springboot
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: tranquil_springboot
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/salud_mental?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12345678
    networks:
      - tranquil_net

  # Backend de Chat (Django)
  django-app:
    build:
      context: ./Tranquil_Connect_Django
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: tranquil_django
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py makemigrations && 
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    networks:
      - tranquil_net

  # Servidor Proxy (Nginx)
  nginx:
    image: nginx:stable-alpine
    container_name: tranquil_nginx
    depends_on:
      - springboot-app
      - django-app
    ports:
      - "80:80"
    volumes:
      # Montamos el archivo en la ruta estándar de configuración de sitios de Nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - tranquil_net

networks:
  tranquil_net:
    driver: bridge