# Generated by Django 5.2.12 on 2026-03-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField(db_column='usuario_id')),
                ('mensaje_usuario', models.TextField(db_column='mensaje_usuario')),
                ('respuesta_bot', models.TextField(db_column='respuesta_bot')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, db_column='fecha_envio')),
            ],
            options={
                'db_table': 'historial_chatbot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_grupo', models.IntegerField(db_column='id_grupo')),
                ('id_usuario', models.IntegerField(db_column='id_usuario')),
                ('contenido', models.TextField(blank=True, null=True)),
                ('imagen_url', models.ImageField(blank=True, null=True, upload_to='chat_fotos/')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mensajes_chat',
                'managed': False,
            },
        ),
    ]
